### ISSUE TITLE
Migrate after importing production database

### ISSUE THREAD

**Issue by mrk-j** [digifactory/laravel-pull-production-data#12]
Maybe we can run `php artisan migrate` after the production data has been imported. That way all new migrations will run without manually running the migrations.

@m-bosch what do you think?

**Comment by m-bosch** [comment]
Hi @mrk-j, 

I think this will improve the proces so it is a good idea.

**Comment by m-bosch** [comment]
@mrk-j  I think we can add this as an artisan call in the new option of #29? Maybe even as a default to add the `migrate` artisan call?

**Comment by m-bosch** [comment]
We have put this suggestion in PR #29.
