### ISSUE TITLE
Run scripts after pulling production data is complete

### ISSUE THREAD

**Issue by mrk-j** [digifactory/laravel-pull-production-data#22]
I think we should create an option to configure some kind of classes that contain code to anonymize or in any other way alter data after pulling the production data. 

Maybe we can (re-)seed the database after pulling the production backup so we always have a specific account available?

**Comment by m-bosch** [comment]
Perhaps it is an idea to extend the config file with an array of commands that need to be run when the "ppd" is done?

**Comment by m-bosch** [comment]
Hi @mrk-j,

We recently made a new PR for this. When this is reviewed the option is available.

**Comment by m-bosch** [comment]
When #29 is merged this issue will be released. 
The estimate is to complete this before 2025 :-)
